(self.AMP=self.AMP||[]).push({n:"amp-accordion",v:"1812131718380",f:(function(AMP,_){
var h="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},l;if("function"==typeof Object.setPrototypeOf)l=Object.setPrototypeOf;else{var m;a:{var n={a:!0},p={};try{p.__proto__=n;m=p.a;break a}catch(a){}m=!1}l=m?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var q=l;function r(){var a,b;this.promise=new Promise(function(c,d){a=c;b=d});this.resolve=a;this.reject=b};self.log=self.log||{user:null,dev:null,userForEmbed:null};var t=self.log;function u(){if(!t.user)throw Error("failed to call initLogConstructor");return t.user}function v(){if(t.dev)return t.dev;throw Error("failed to call initLogConstructor");};function w(a){var b=!a.nodeType;if(b){var c=a,d=x(c);d=y(d);return z(d,"action")}d=(a.ownerDocument||a).defaultView;var e=d!=(d.__AMP_TOP||d);if(e)return(d=d!=(d.__AMP_TOP||d)&&A(d,"action")?z(d,"action"):null)?d:null;d=x(a);d=y(d);return A(d,"action")?z(d,"action"):null}function B(a,b){a=a.__AMP_TOP||a;return z(a,b)}function x(a){return a.nodeType?B((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function y(a){a=x(a);return a.isSingleDoc()?a.win:a}
function z(a,b){A(a,b);var c=a.services;c||(c=a.services={});var d=c;a=d[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function A(a,b){a=a.services&&a.services[b];return!(!a||!a.ctor&&!a.obj)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function C(a,b,c){for(var d=a;d&&d!==c;d=d.parentElement)if(b(d))return d;return null};function D(a,b,c,d){var e=new E(a,b,c,d);return e.solveYValueFromXValue.bind(e)}function E(a,b,c,d){var e=1,f=1;this.y0=this.x0=0;this.x1=a;this.y1=b;this.x2=c;this.y2=d;this.x3=e;this.y3=f}E.prototype.solveYValueFromXValue=function(a){return this.getPointY(this.solvePositionFromXValue(a))};
E.prototype.solvePositionFromXValue=function(a){var b=1E-6,c=(a-this.x0)/(this.x3-this.x0);if(0>=c)return 0;if(1<=c)return 1;for(var d=0,e=1,f=0,g=0;8>g;g++){f=this.getPointX(c);var k=(this.getPointX(c+b)-f)/b;if(Math.abs(f-a)<b)return c;if(Math.abs(k)<b)break;else f<a?d=c:e=c,c-=(f-a)/k}for(g=0;Math.abs(f-a)>b&&8>g;g++)f<a?(d=c,c=(c+e)/2):(e=c,c=(c+d)/2),f=this.getPointX(c);return c};
E.prototype.getPointX=function(a){if(0==a)return this.x0;if(1==a)return this.x3;var b=this.lerp(this.x0,this.x1,a),c=this.lerp(this.x1,this.x2,a),d=this.lerp(this.x2,this.x3,a);b=this.lerp(b,c,a);c=this.lerp(c,d,a);return this.lerp(b,c,a)};E.prototype.getPointY=function(a){if(0==a)return this.y0;if(1==a)return this.y3;var b=this.lerp(this.y0,this.y1,a),c=this.lerp(this.y1,this.y2,a),d=this.lerp(this.y2,this.y3,a);b=this.lerp(b,c,a);c=this.lerp(c,d,a);return this.lerp(b,c,a)};
E.prototype.lerp=function(a,b,c){return a+c*(b-a)};var aa=D(.25,.1,.25,1),ba=D(.42,0,1,1),ca=D(0,0,.58,1),da=D(.42,0,.58,1),ea={linear:function(a){return a},ease:aa,"ease-in":ba,"ease-out":ca,"ease-in-out":da};
function F(a){if(!a)return null;if("string"==typeof a){if(-1!=a.indexOf("cubic-bezier")){var b=a.match(/cubic-bezier\((.+)\)/);if(b&&(b=b[1].split(",").map(parseFloat),4==b.length)){for(var c=0;4>c;c++)if(isNaN(b[c]))return null;return D(b[0],b[1],b[2],b[3])}return null}return ea[a]}return a};function fa(){}function G(a){var b;this.j=a;(a=b)||(a=B(self,"vsync"));this.o=a;this.D=null;this.c=[]}function H(a,b,c,d){return(new G(a)).setCurve(d).add(0,b,1).start(c)}G.prototype.setCurve=function(a){a&&(this.D=F(a));return this};G.prototype.add=function(a,b,c,d){this.c.push({delay:a,func:b,duration:c,curve:F(d)});return this};G.prototype.start=function(a){var b=new I(this.o,this.j,this.c,this.D,a);return b};
function I(a,b,c,d,e){this.o=a;this.j=b;this.c=[];for(b=0;b<c.length;b++){var f=c[b];this.c.push({delay:f.delay,func:f.func,duration:f.duration,curve:f.curve||d,started:!1,completed:!1})}this.J=e;this.N=Date.now();this.A=!0;this.G={};e=new r;this.F=e.promise;this.M=e.resolve;this.L=e.reject;this.H=this.o.createAnimTask(this.j,{mutate:this.O.bind(this)});this.o.canAnimate(this.j)?this.H(this.G):(v().warn("Animation","cannot animate"),J(this,!1,0))}
I.prototype.then=function(a,b){return a||b?this.F.then(a,b):this.F};I.prototype.thenAlways=function(a){a=a||fa;return this.then(a,a)};I.prototype.halt=function(a){J(this,!1,a||0)};function J(a,b,c){if(a.A){a.A=!1;if(0!=c){1<a.c.length&&a.c.sort(function(a,b){return a.delay+a.duration-(b.delay+b.duration)});try{if(0<c)for(c=0;c<a.c.length;c++)a.c[c].func(1,!0);else for(var d=a.c.length-1;0<=d;d--)a.c[d].func(0,!1)}catch(e){v().error("Animation","completion failed: "+e,e),b=!1}}b?a.M():a.L()}}
I.prototype.O=function(){if(this.A){for(var a=Date.now(),b=Math.min((a-this.N)/this.J,1),c=0;c<this.c.length;c++){var d=this.c[c];!d.started&&b>=d.delay&&(d.started=!0)}for(c=0;c<this.c.length;c++)if(d=this.c[c],d.started&&!d.completed)a:{var e;if(0<d.duration){var f=e=Math.min((b-d.delay)/d.duration,1);if(d.curve&&1!=f)try{f=d.curve(e)}catch(g){v().error("Animation","step curve failed: "+g,g);J(this,!1,0);break a}}else f=e=1;1==e&&(d.completed=!0);try{d.func(f,d.completed)}catch(g){v().error("Animation",
"step mutate failed: "+g,g),J(this,!1,0)}}1==b?J(this,!0,0):this.o.canAnimate(this.j)?this.H(this.G):(v().warn("Animation","cancel animation"),J(this,!1,0))}};var K,L="Webkit webkit Moz moz ms O o".split(" ");function M(a,b,c){if(2>b.length?0:0==b.lastIndexOf("--",0))return b;K||(K=Object.create(null));var d=K[b];if(!d||c){d=b;if(void 0===a[b]){var e=b.charAt(0).toUpperCase()+b.slice(1);a:{for(var f=0;f<L.length;f++){var g=L[f]+e;if(void 0!==a[g]){e=g;break a}}e=""}var k=e;void 0!==a[k]&&(d=k)}c||(K[b]=d)}return d}function N(a,b,c){var d;(b=M(a.style,b,void 0))&&(a.style[b]=d?c+d:c)}function O(a,b){for(var c in b)N(a,c,b[c])};function P(a,b){return function(c,d){for(var e in b){var f=e;"display"===f&&v().error("STYLE","`display` style detected. You must use toggle instead.");N(a,f,b[e](c,d))}}}function Q(a,b){return function(c){return a+(b-a)*c}}function R(a){return function(b){return a(b)+"px"}};var ga=D(.47,0,.745,.715),ha=D(.39,.575,.565,1);function S(a){var b=AMP.BaseElement.call(this,a)||this;b.m=[];b.B=null;b.l=null;b.C=!1;b.h=null;b.w=null;b.P=a.id?a.id:Math.floor(100*Math.random());return b}var T=AMP.BaseElement;S.prototype=h(T.prototype);S.prototype.constructor=S;if(q)q(S,T);else for(var U in T)if("prototype"!=U)if(Object.defineProperties){var V=Object.getOwnPropertyDescriptor(T,U);V&&Object.defineProperty(S,U,V)}else S[U]=T[U];S.R=T.prototype;
S.prototype.isLayoutSupported=function(a){return"container"==a};
S.prototype.buildCallback=function(){var a=this;this.w=w(this.element);this.C=this.element.hasAttribute("disable-session-states");this.B=ia(this);this.l=ja(this);this.h=this.getRealChildren();this.h.forEach(function(b,c){u().assert("section"==b.tagName.toLowerCase(),"Sections should be enclosed in a <section> tag, See https://github.com/ampproject/amphtml/blob/master/extensions/amp-accordion/amp-accordion.md. Found in: %s",a.element);var d=b.children;u().assert(2==d.length,"Each section must have exactly two children. See https://github.com/ampproject/amphtml/blob/master/extensions/amp-accordion/amp-accordion.md. Found in: %s",
a.element);var e=d[1];e.classList.add("i-amphtml-accordion-content");var f=e.getAttribute("id");f||(f=a.P+"_AMP_content_"+c,e.setAttribute("id",f));a.registerAction("toggle",function(b){if(b.args){var c=b.args.section,d=a.getAmpDoc().getElementById(c);d=u().assertElement(d);u().assert(d,"No element found with id: %s",c);W(a,d)}else for(var e=0;e<a.h.length;e++)W(a,a.h[e])});a.registerAction("expand",function(b){if(b.args){b=b.args.section;var c=a.getAmpDoc().getElementById(b);c=u().assertElement(c);
u().assert(c,"No element found with id: %s",b);W(a,c,!0)}else for(b=0;b<a.h.length;b++)W(a,a.h[b],!0)});a.registerAction("collapse",function(b){if(b.args){b=b.args.section;var c=a.getAmpDoc().getElementById(b);c=u().assertElement(c);u().assert(c,"No element found with id: %s",b);W(a,c,!1)}else for(b=0;b<a.h.length;b++)W(a,a.h[b],!1)});a.l[f]?b.setAttribute("expanded",""):!1===a.l[f]&&b.removeAttribute("expanded");a.mutateElement(function(){});c=d[0];c.classList.add("i-amphtml-accordion-header");c.setAttribute("role",
"button");c.setAttribute("aria-controls",f);c.setAttribute("aria-expanded",b.hasAttribute("expanded").toString());c.hasAttribute("tabindex")||c.setAttribute("tabindex",0);a.m.push(c);c.addEventListener("click",a.I.bind(a));c.addEventListener("keydown",a.K.bind(a))})};function ia(a){var b=a.element.id||a.element.getResourceId();a=a.win.location.href;var c=a.indexOf("#");return"amp-"+b+"-"+(-1==c?a:a.substring(0,c))}
function ja(a){if(a.C)return{};try{var b=a.win.sessionStorage.getItem(a.B);return b?JSON.parse(b):{}}catch(c){return{}}}function ka(a){if(!a.C){var b=JSON.stringify(a.l);try{a.win.sessionStorage.setItem(a.B,b)}catch(c){}}}
function X(a,b,c){var d=a.win;var e="accordionSection."+b;var f={};var g={detail:f};Object.assign(g,void 0);"function"==typeof d.CustomEvent?e=new d.CustomEvent(e,g):(d=d.document.createEvent("CustomEvent"),d.initCustomEvent(e,!!g.bubbles,!!g.cancelable,f),e=d);a.w.trigger(c,b,e,100);a.element.dispatchCustomEvent(b)}
function W(a,b,c){var d=b.children,e=d[0];d=d[1].getAttribute("id");var f=b.hasAttribute("expanded"),g=void 0==c?!b.hasAttribute("expanded"):c;g&&b.hasAttribute("expanded")||!g&&!b.hasAttribute("expanded")||(a.element.hasAttribute("animate")?g?(e.setAttribute("aria-expanded","true"),la(a,b),a.element.hasAttribute("expand-single-section")&&a.h.forEach(function(c){c!=b&&(Y(a,c),c.children[0].setAttribute("aria-expanded","false"))})):(e.setAttribute("aria-expanded","false"),Y(a,b)):a.mutateElement(function(){g?
(X(a,"expand",b),b.setAttribute("expanded",""),e.setAttribute("aria-expanded","true"),a.element.hasAttribute("expand-single-section")&&a.h.forEach(function(c){c!=b&&(c.hasAttribute("expanded")&&(X(a,"collapse",c),c.removeAttribute("expanded")),c.children[0].setAttribute("aria-expanded","false"))})):(X(a,"collapse",b),b.removeAttribute("expanded"),e.setAttribute("aria-expanded","false"))},b),a.l[d]=!f,ka(a))}
function la(a,b){var c,d,e=b.children[1];a.mutateElement(function(){var c={position:"fixed",opacity:"0"},d=e.style,k;for(k in c)d.setProperty(M(d,k),c[k].toString(),"important");b.hasAttribute("expanded")||(X(a,"expand",b),b.setAttribute("expanded",""))}).then(function(){return a.measureMutateElement(function(){c=e.offsetHeight;var b=a.getViewport().getHeight();d=Z(Math.abs(c),b)},function(){O(e,{position:"",opacity:"",height:0})})}).then(function(){return H(a.element,P(e,{height:R(Q(0,c)),opacity:Q(0,
1)}),d,ga).thenAlways(function(){a.mutateElement(function(){O(e,{height:"",opacity:""})})})})}function Y(a,b){var c,d,e=b.children[1];a.measureElement(function(){c=b.offsetHeight;var e=a.getViewport().getSize().height;d=Z(Math.abs(c),e)}).then(function(){return H(e,P(e,{height:R(Q(c,0))}),d,ha).thenAlways(function(){return a.mutateElement(function(){b.hasAttribute("expanded")&&(X(a,"collapse",b),b.removeAttribute("expanded"));O(e,{height:""})})})})}
function Z(a,b){var c=void 0===c?200:c;var d=void 0===d?500:d;var e=Math.abs(a)/b*d;return Math.min(Math.max(e,c),d)}S.prototype.I=function(a){ma(this,a)&&(a.preventDefault(),W(this,a.currentTarget.parentElement))};function ma(a,b){var c=b.target;b=b.currentTarget;var d=!!C(c,function(a){return"A"==a.tagName},b),e=a.w.hasAction(c,"tap",b);return!d&&!e}
S.prototype.K=function(a){if(!a.defaultPrevented)switch(a.key){case "ArrowUp":case "ArrowDown":var b=this.m.indexOf(a.currentTarget);if(-1!==b){a.preventDefault();a=(b+("ArrowUp"==a.key?-1:1))%this.m.length;0>a&&(a+=this.m.length);try{this.m[a].focus()}catch(c){}}break;case "Enter":case " ":a.target==a.currentTarget&&(a.preventDefault(),W(this,a.currentTarget.parentElement))}};(function(a){a.registerElement("amp-accordion",S)})(self.AMP);
})});
//# sourceMappingURL=amp-accordion-0.1.js.map

